# Generated by Django 5.0 on 2024-02-08 00:25

import app.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('cor_code', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'cor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estilo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FotosRoupas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roupa_id', models.IntegerField(blank=True, null=True)),
                ('fotoUrl', models.ImageField(upload_to=app.utils.generate_file_name)),
                ('ordem', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'fotosRoupa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Locacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('roupa_id', models.IntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'locacoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tamanho',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tamanho',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProdutoVariacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preco_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cor')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estilo')),
            ],
            options={
                'db_table': 'produto_variacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FotosRoupaVariacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fotoUrl', models.ImageField(upload_to=app.utils.generate_file_name)),
                ('ordem', models.IntegerField(default=0)),
                ('variacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produtovariacao')),
            ],
            options={
                'db_table': 'fotos_roupa_variacao',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roupas',
            fields=[
                ('id_roupas', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('preco_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponibilidade', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('cor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cor')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estilo')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tamanho')),
            ],
            options={
                'db_table': 'roupas',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.roupas'),
        ),
        migrations.AddField(
            model_name='produtovariacao',
            name='tamanho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tamanho'),
        ),
    ]
