# Generated by Django 5.0 on 2024-01-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Locacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('roupa_id', models.IntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'locacoes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roupas',
            fields=[
                ('id_roupas', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('tamanho', models.IntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=200, null=True)),
                ('estilo', models.CharField(blank=True, max_length=200, null=True)),
                ('preco_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponibilidade', models.IntegerField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'roupas',
                'managed': True,
            },
        ),
    ]
