# Generated by Django 5.0 on 2024-02-08 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fotosroupas',
            name='roupa_id',
        ),
        migrations.AddField(
            model_name='fotosroupas',
            name='roupa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.roupas'),
            preserve_default=False,
        ),
    ]
