# Generated by Django 4.1.5 on 2023-12-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppRoupas',
            fields=[
                ('id_roupas', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('tamanho', models.IntegerField(blank=True, null=True)),
                ('cor', models.CharField(blank=True, max_length=200, null=True)),
                ('estilo', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'app_roupas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_clientes', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=200, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField(blank=True, null=True)),
                ('roupa_id', models.IntegerField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'locacoes',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='roupas',
            options={'managed': False},
        ),
    ]
