# Generated by Django 4.1.5 on 2024-01-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_roupas_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotosRoupas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('roupa_id', models.IntegerField(blank=True, null=True)),
                ('fotoUrl', models.ImageField(upload_to='%Y/%m/%d/')),
                ('ordem', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'fotosRoupa',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='roupas',
            name='tamanho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
