# Generated by Django 5.0 on 2024-02-15 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_fotosroupas_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtovariacao',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='produtovariacao',
            name='estilo',
        ),
        migrations.RemoveField(
            model_name='roupas',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='roupas',
            name='disponibilidade',
        ),
        migrations.RemoveField(
            model_name='roupas',
            name='preco_aluguel',
        ),
        migrations.RemoveField(
            model_name='roupas',
            name='tamanho',
        ),
    ]
