# Generated by Django 4.1.5 on 2023-12-21 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_approupas_clientes_locacoes_alter_roupas_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roupas',
            table='roupas',
        ),
    ]
