# Generated by Django 5.0 on 2024-02-21 23:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_produtovariacao_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locacoes',
            old_name='valor_aluguel',
            new_name='valor_total',
        ),
        migrations.RemoveField(
            model_name='locacoes',
            name='roupa_id',
        ),
        migrations.AddField(
            model_name='locacoes',
            name='data_negociacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='fotosroupas',
            table='fotos_roupa',
        ),
        migrations.CreateModel(
            name='ItensLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.locacoes')),
                ('produto_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produtovariacao')),
            ],
            options={
                'db_table': 'itens_locacao',
                'managed': True,
            },
        ),
    ]
