# Generated by Django 5.0 on 2024-02-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_valor_aluguel_locacoes_valor_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacoes',
            name='endereco_bairro',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locacoes',
            name='endereco_cep',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locacoes',
            name='endereco_cidade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locacoes',
            name='endereco_complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locacoes',
            name='endereco_numero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='locacoes',
            name='endereco_rua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
